language: go
go:
- 1.10.x
install:
- go get gopkg.in/alecthomas/gometalinter.v1
- go get github.com/gordonklaus/ineffassign
- go get github.com/jgautheron/goconst/cmd/goconst
- go get github.com/kisielk/errcheck
- go get github.com/golang/dep/cmd/dep
- dep ensure
script:
- gometalinter.v1 --vendor --disable-all --enable=vet --enable=ineffassign --enable=goconst
  --tests ./...
- go test -v -race ./...
before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"
before_deploy:
- go get github.com/goreleaser/goreleaser
deploy:
- provider: script
  script: goreleaser
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
- bonsai/generate-sha512sum.sh
- bonsai/github-release-upload.sh github_api_token=$GITHUB_TOKEN repo_slug="$TRAVIS_REPO_SLUG"
  tag="${TRAVIS_TAG}" filename="dist/$(cat dist/sha512_file)"
env:
  global:
    secure: HbMmDjTmUNFvO8jMMRGug+ugr5trKJtDz3C8gynmfQB3K+yEcokmckIZHN/vTwACMQO0+uaL5uY9UopyvLFp8Dl2u12z8MOGwv0ag47+Wmg4CaDUOBChvZNiBQbjodmUbZFjvSZQvEBJ54eaQxnvdrReGL7VP5B2DJQE+40dQbewF4z7wKAlu8lBrI5bsM30l5ugQ3VVLaai27Dd+HjQWkSHNoC1cg6ikM2Hf8vepUoUh8tUbF6X0U+mkwX7OsJfHKCfcYyxu87Xcy6DKMVEketiriNrV+cpqZm1bGG+QTGYdBCQKiAHZUpnx3ZJBgj7X2suNY/y9x0Ji4opht+EScQKJjO883/6LlI8Nq8pexXGbBhLE4xvwZGyu6l+8Lg2GlxU3ro8lZ4KPaL4mxbK/OhmlOL4AZXYi7XalwgsvJXqngneouUAvtN2CCkLqi5+G3U8AnfI9feXX219hynRov/YdBHC2Eu3OfVvLSAnnyo5S6MAsRwJarFVWZwcEcs0tPi6+ya7E555KLFChwrZ3wtWvI88kko194nf5XH0nEm11iAeYCGwlYMyzWV9eztabDBWeTin9gTgvblVYZxkf1WbJtQbHRDYX/LLRhXkTcQqwUuFLhwEGKmcfH/HVOrthhvkoFIrRUAuroyshMjAtgJ8vOdpgUi3/RdDTDtmYfw=
